/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedTechnicalCalculationsRouteImport } from './routes/_authenticated.technical-calculations'
import { Route as AuthenticatedSelectionWizardRouteImport } from './routes/_authenticated.selection-wizard'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated.products'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated.materials'
import { Route as AuthenticatedLeaveManagementRouteImport } from './routes/_authenticated.leave-management'
import { Route as AuthenticatedFixedCostsRouteImport } from './routes/_authenticated.fixed-costs'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTechnicalCalculationsRoute =
  AuthenticatedTechnicalCalculationsRouteImport.update({
    id: '/technical-calculations',
    path: '/technical-calculations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSelectionWizardRoute =
  AuthenticatedSelectionWizardRouteImport.update({
    id: '/selection-wizard',
    path: '/selection-wizard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveManagementRoute =
  AuthenticatedLeaveManagementRouteImport.update({
    id: '/leave-management',
    path: '/leave-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFixedCostsRoute = AuthenticatedFixedCostsRouteImport.update({
  id: '/fixed-costs',
  path: '/fixed-costs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/fixed-costs': typeof AuthenticatedFixedCostsRoute
  '/leave-management': typeof AuthenticatedLeaveManagementRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/selection-wizard': typeof AuthenticatedSelectionWizardRoute
  '/technical-calculations': typeof AuthenticatedTechnicalCalculationsRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/fixed-costs': typeof AuthenticatedFixedCostsRoute
  '/leave-management': typeof AuthenticatedLeaveManagementRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/selection-wizard': typeof AuthenticatedSelectionWizardRoute
  '/technical-calculations': typeof AuthenticatedTechnicalCalculationsRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/fixed-costs': typeof AuthenticatedFixedCostsRoute
  '/_authenticated/leave-management': typeof AuthenticatedLeaveManagementRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/selection-wizard': typeof AuthenticatedSelectionWizardRoute
  '/_authenticated/technical-calculations': typeof AuthenticatedTechnicalCalculationsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/documents'
    | '/fixed-costs'
    | '/leave-management'
    | '/materials'
    | '/products'
    | '/selection-wizard'
    | '/technical-calculations'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/documents'
    | '/fixed-costs'
    | '/leave-management'
    | '/materials'
    | '/products'
    | '/selection-wizard'
    | '/technical-calculations'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/fixed-costs'
    | '/_authenticated/leave-management'
    | '/_authenticated/materials'
    | '/_authenticated/products'
    | '/_authenticated/selection-wizard'
    | '/_authenticated/technical-calculations'
    | '/_authenticated/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/technical-calculations': {
      id: '/_authenticated/technical-calculations'
      path: '/technical-calculations'
      fullPath: '/technical-calculations'
      preLoaderRoute: typeof AuthenticatedTechnicalCalculationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/selection-wizard': {
      id: '/_authenticated/selection-wizard'
      path: '/selection-wizard'
      fullPath: '/selection-wizard'
      preLoaderRoute: typeof AuthenticatedSelectionWizardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave-management': {
      id: '/_authenticated/leave-management'
      path: '/leave-management'
      fullPath: '/leave-management'
      preLoaderRoute: typeof AuthenticatedLeaveManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fixed-costs': {
      id: '/_authenticated/fixed-costs'
      path: '/fixed-costs'
      fullPath: '/fixed-costs'
      preLoaderRoute: typeof AuthenticatedFixedCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFixedCostsRoute: typeof AuthenticatedFixedCostsRoute
  AuthenticatedLeaveManagementRoute: typeof AuthenticatedLeaveManagementRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSelectionWizardRoute: typeof AuthenticatedSelectionWizardRoute
  AuthenticatedTechnicalCalculationsRoute: typeof AuthenticatedTechnicalCalculationsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFixedCostsRoute: AuthenticatedFixedCostsRoute,
  AuthenticatedLeaveManagementRoute: AuthenticatedLeaveManagementRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSelectionWizardRoute: AuthenticatedSelectionWizardRoute,
  AuthenticatedTechnicalCalculationsRoute:
    AuthenticatedTechnicalCalculationsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
