from __future__ import annotations

from datetime import datetime, timedelta
from email.message import EmailMessage
from email.utils import formataddr
import hashlib
import os
import re
import secrets
import smtplib
from typing import Any


from app.core.db import get_database_backend
from app.core.security import hash_password


EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
SIGNUP_ALLOWED_EMAIL_DOMAIN = "@bomaksan.com"
EMAIL_VERIFICATION_EXPIRY_HOURS = 24
PASSWORD_RESET_EXPIRY_MINUTES = 30
VERIFICATION_SEND_RATE_LIMIT = (3, 10)
VERIFICATION_VERIFY_RATE_LIMIT = (5, 10)
PASSWORD_RESET_SEND_RATE_LIMIT = (3, 10)
PASSWORD_RESET_VERIFY_RATE_LIMIT = (5, 10)
SIGNUP_DEFAULT_ROLE_NAMES = ("Kullanici", "Kullanıcı")
_ACCOUNT_SECURITY_SCHEMA_READY = False


def _send_email(to_email: str, subject: str, body: str, html_body: str | None = None) -> dict[str, str]:
    host = os.getenv("BOMAKSAN_SMTP_HOST", "").strip()
    from_email = os.getenv("BOMAKSAN_SMTP_FROM", "").strip()
    username = os.getenv("BOMAKSAN_SMTP_USER", "").strip()
    password = os.getenv("BOMAKSAN_SMTP_PASSWORD", "")
    port = int(os.getenv("BOMAKSAN_SMTP_PORT", "587") or 587)
    use_tls = str(os.getenv("BOMAKSAN_SMTP_USE_TLS", "true")).strip().lower() not in {"0", "false", "no", "off"}

    if not host or not from_email:
        return {
            "status": "smtp_not_configured",
            "message": "SMTP ayarı bulunamadı. Şifre sıfırlama kodu gönderilemedi.",
        }

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = formataddr(("Bomaksan Maliyet Analizleri", from_email))
    message["To"] = to_email
    message.set_content(body)
    if html_body:
        message.add_alternative(html_body, subtype="html")

    with smtplib.SMTP(host, port, timeout=30) as smtp:
        smtp.ehlo()
        if use_tls:
            smtp.starttls()
            smtp.ehlo()
        if username:
            smtp.login(username, password)
        smtp.send_message(message)

    return {"status": "sent", "message": f"E-posta {to_email} adresine gönderildi."}


def _column_exists(connection: Any, table_name: str, column_name: str) -> bool:
    cursor = connection.cursor()
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        LIMIT 1
        """,
        (table_name, column_name),
    )
    return cursor.fetchone() is not None


def _table_exists(cursor: Any, table_name: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = %s
        LIMIT 1
        """,
        (table_name,),
    )
    return cursor.fetchone() is not None


def ensure_account_security_schema(connection: Any) -> None:
    global _ACCOUNT_SECURITY_SCHEMA_READY
    if _ACCOUNT_SECURITY_SCHEMA_READY:
        return

    cursor = connection.cursor()
    backend = get_database_backend()
    if not _column_exists(connection, "kullanicilar", "email"):
        cursor.execute("ALTER TABLE kullanicilar ADD COLUMN email VARCHAR(255) NULL")
    if not _column_exists(connection, "kullanicilar", "email_verified"):
        cursor.execute("ALTER TABLE kullanicilar ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE")
    if not _column_exists(connection, "kullanicilar", "is_active"):
        cursor.execute("ALTER TABLE kullanicilar ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE")
    if not _column_exists(connection, "kullanicilar", "email_verified_at"):
        cursor.execute("ALTER TABLE kullanicilar ADD COLUMN email_verified_at TIMESTAMP NULL")
    if not _column_exists(connection, "kullanicilar", "failed_login_attempts"):
        cursor.execute("ALTER TABLE kullanicilar ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0")
    if not _column_exists(connection, "kullanicilar", "locked_until"):
        cursor.execute("ALTER TABLE kullanicilar ADD COLUMN locked_until TIMESTAMP NULL")
    if not _column_exists(connection, "kullanicilar", "module_permissions"):
        column_type = "JSONB" if backend == "postgres" else "JSON"
        cursor.execute(f"ALTER TABLE kullanicilar ADD COLUMN module_permissions {column_type} NULL")
    if not _column_exists(connection, "kullanicilar", "mobile_module_permissions"):
        column_type = "JSONB" if backend == "postgres" else "JSON"
        cursor.execute(f"ALTER TABLE kullanicilar ADD COLUMN mobile_module_permissions {column_type} NULL")

    _ensure_postgres_auth_tables(cursor)
    connection.commit()
    _ACCOUNT_SECURITY_SCHEMA_READY = True


def _ensure_postgres_auth_tables(cursor: Any) -> None:
    if not _table_exists(cursor, "email_verification_tokens"):
        cursor.execute(
            """
            CREATE TABLE email_verification_tokens (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES kullanicilar(id) ON DELETE CASCADE,
                token_hash VARCHAR(64) NOT NULL,
                expires_at TIMESTAMP NOT NULL,
                used_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        cursor.execute("CREATE INDEX idx_evt_user_id ON email_verification_tokens (user_id)")
        cursor.execute("CREATE INDEX idx_evt_token_hash ON email_verification_tokens (token_hash)")

    if not _table_exists(cursor, "password_reset_tokens"):
        cursor.execute(
            """
            CREATE TABLE password_reset_tokens (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES kullanicilar(id) ON DELETE CASCADE,
                reset_code_hash VARCHAR(64) NOT NULL,
                expires_at TIMESTAMP NOT NULL,
                used_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        cursor.execute("CREATE INDEX idx_prt_user_id ON password_reset_tokens (user_id)")
        cursor.execute("CREATE INDEX idx_prt_reset_code_hash ON password_reset_tokens (reset_code_hash)")

    if not _table_exists(cursor, "auth_rate_limits"):
        cursor.execute(
            """
            CREATE TABLE auth_rate_limits (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                action_type VARCHAR(64) NOT NULL,
                target_key VARCHAR(255) NOT NULL,
                window_started_at TIMESTAMP NOT NULL,
                attempt_count INT NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_auth_rate_limits_action_target UNIQUE (action_type, target_key)
            )
            """
        )

def validate_email(email: str) -> str:
    normalized = str(email or "").strip().lower()
    if not normalized:
        raise ValueError("E-posta adresini girin.")
    if not EMAIL_REGEX.match(normalized):
        raise ValueError("Geçerli bir e-posta adresi girin.")
    return normalized


def validate_signup_email(email: str) -> str:
    normalized = validate_email(email)
    if not normalized.endswith(SIGNUP_ALLOWED_EMAIL_DOMAIN):
        raise ValueError("Sadece @bomaksan.com uzantılı e-posta adresleri ile kayıt olabilirsiniz.")
    return normalized


def validate_password_policy(password: str) -> None:
    if len(str(password or "")) < 8:
        raise ValueError("Şifre en az 8 karakter olmalıdır.")


def consume_rate_limit(
    connection: Any,
    action_type: str,
    target_key: str,
    limit_count: int,
    window_minutes: int,
    message: str,
) -> None:
    normalized_key = str(target_key or "").strip().lower()
    if not normalized_key:
        return
    now = datetime.now()
    cursor = connection.cursor(dictionary=True)
    cursor.execute(
        """
        SELECT id, attempt_count, window_started_at
        FROM auth_rate_limits
        WHERE action_type = %s AND target_key = %s
        LIMIT 1
        """,
        (action_type, normalized_key),
    )
    row = cursor.fetchone()
    if not row:
        cursor.execute(
            """
            INSERT INTO auth_rate_limits (action_type, target_key, window_started_at, attempt_count)
            VALUES (%s, %s, %s, %s)
            """,
            (action_type, normalized_key, now, 1),
        )
        return

    elapsed_seconds = max(0, int((now - row["window_started_at"]).total_seconds()))
    window_seconds = window_minutes * 60
    if elapsed_seconds >= window_seconds:
        cursor.execute(
            "UPDATE auth_rate_limits SET window_started_at = %s, attempt_count = %s, updated_at = %s WHERE id = %s",
            (now, 1, now, row["id"]),
        )
        return
    if int(row["attempt_count"] or 0) >= limit_count:
        retry_after_minutes = max(1, (window_seconds - elapsed_seconds + 59) // 60)
        raise ValueError(f"{message} Lütfen {retry_after_minutes} dakika sonra tekrar deneyin.")
    cursor.execute(
        "UPDATE auth_rate_limits SET attempt_count = attempt_count + 1, updated_at = %s WHERE id = %s",
        (now, row["id"]),
    )


def _token_hash(token: str) -> str:
    return hashlib.sha256(str(token or "").encode("utf-8")).hexdigest()


def _create_numeric_code() -> str:
    return f"{secrets.randbelow(1000000):06d}"


def _find_user_by_email(connection: Any, email: str) -> dict[str, Any] | None:
    cursor = connection.cursor(dictionary=True)
    cursor.execute(
        """
        SELECT id, kullanici_adi, email, email_verified, is_active
        FROM kullanicilar
        WHERE LOWER(email) = LOWER(%s)
        LIMIT 1
        """,
        (validate_email(email),),
    )
    return cursor.fetchone()


def _find_user_by_identifier(connection: Any, identifier: str) -> dict[str, Any] | None:
    normalized = str(identifier or "").strip()
    if not normalized:
        return None
    cursor = connection.cursor(dictionary=True)
    cursor.execute(
        """
        SELECT id, kullanici_adi, email, email_verified, is_active
        FROM kullanicilar
        WHERE LOWER(kullanici_adi) = LOWER(%s) OR LOWER(email) = LOWER(%s)
        LIMIT 1
        """,
        (normalized, normalized),
    )
    return cursor.fetchone()


def _verification_email_content(username: str, code: str) -> tuple[str, str, str]:
    subject = "Bomaksan hesabınızı doğrulayın"
    body = (
        f"Merhaba {username},\n\n"
        "Bomaksan Maliyet Analizleri hesabınız için e-posta doğrulama talebi alındı.\n\n"
        f"Doğrulama kodunuz: {code}\n"
        f"Bu kod {EMAIL_VERIFICATION_EXPIRY_HOURS} saat boyunca geçerlidir.\n\n"
        "Bu işlemi siz yapmadıysanız bu e-postayı dikkate almayabilirsiniz."
    )
    html_body = f"""
    <html><body style="margin:0;padding:24px;background:#f5f5f5;font-family:Arial,sans-serif;color:#222;"><div style="max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #e5e5e5;border-radius:12px;padding:32px;"><div style="font-size:20px;font-weight:700;color:#b71c1c;margin-bottom:20px;">Bomaksan Maliyet Analizleri</div><p>Merhaba {username},</p><p>Hesabınız için bir e-posta doğrulama talebi alındı.</p><p>Aşağıdaki kodu web giriş ekranındaki <strong>E-posta Doğrula</strong> alanına girin:</p><div style="margin:16px 0 20px 0;padding:16px;text-align:center;font-size:28px;font-weight:700;letter-spacing:6px;background:#fafafa;border:1px solid #e0e0e0;border-radius:10px;">{code}</div><p>Bu kod {EMAIL_VERIFICATION_EXPIRY_HOURS} saat boyunca geçerlidir.</p><p style="color:#666;">Bu işlemi siz yapmadıysanız bu e-postayı dikkate almayabilirsiniz.</p></div></body></html>
    """
    return subject, body, html_body


def _password_reset_email_content(username: str, code: str) -> tuple[str, str, str]:
    subject = "Bomaksan şifre sıfırlama kodunuz"
    body = (
        f"Merhaba {username},\n\n"
        "Bomaksan Maliyet Analizleri hesabınız için şifre sıfırlama talebi alındı.\n\n"
        f"Şifre sıfırlama kodunuz: {code}\n"
        f"Bu kod {PASSWORD_RESET_EXPIRY_MINUTES} dakika boyunca geçerlidir.\n\n"
        "Bu işlemi siz yapmadıysanız bu e-postayı dikkate almayın."
    )
    html_body = f"""
    <html><body style="margin:0;padding:24px;background:#f5f5f5;font-family:Arial,sans-serif;color:#222;"><div style="max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #e5e5e5;border-radius:12px;padding:32px;"><div style="font-size:20px;font-weight:700;color:#b71c1c;margin-bottom:20px;">Bomaksan Maliyet Analizleri</div><p>Merhaba {username},</p><p>Hesabınız için bir şifre sıfırlama talebi alındı.</p><p>Aşağıdaki kodu web giriş ekranındaki <strong>Şifremi Unuttum</strong> alanında kullanın:</p><div style="margin:16px 0 20px 0;padding:16px;text-align:center;font-size:28px;font-weight:700;letter-spacing:6px;background:#fafafa;border:1px solid #e0e0e0;border-radius:10px;">{code}</div><p>Bu kod {PASSWORD_RESET_EXPIRY_MINUTES} dakika boyunca geçerlidir.</p><p style="color:#666;">Bu işlemi siz yapmadıysanız bu e-postayı dikkate almayın.</p></div></body></html>
    """
    return subject, body, html_body


def create_account(connection: Any, username: str, email: str, password: str) -> dict[str, str]:
    ensure_account_security_schema(connection)
    username = str(username or "").strip()
    if not username:
        raise ValueError("Kullanıcı adını girin.")
    email = validate_signup_email(email)
    validate_password_policy(password)
    cursor = connection.cursor(dictionary=True)
    cursor.execute("SELECT id FROM kullanicilar WHERE LOWER(kullanici_adi) = LOWER(%s) LIMIT 1", (username,))
    if cursor.fetchone():
        raise ValueError("Bu kullanıcı adı zaten kullanılıyor.")
    cursor.execute("SELECT id FROM kullanicilar WHERE LOWER(email) = LOWER(%s) LIMIT 1", (email,))
    if cursor.fetchone():
        raise ValueError("Bu e-posta adresi zaten kullanılıyor.")
    role = None
    for role_name in SIGNUP_DEFAULT_ROLE_NAMES:
        cursor.execute("SELECT id FROM roller WHERE LOWER(rol_adi) = LOWER(%s) LIMIT 1", (role_name,))
        role = cursor.fetchone()
        if role:
            break
    if not role:
        raise ValueError("Varsayılan kullanıcı rolü bulunamadı.")
    cursor.execute(
        """
        INSERT INTO kullanicilar (kullanici_adi, email, sifre_hash, rol_id, email_verified, is_active)
        VALUES (%s, %s, %s, %s, FALSE, FALSE)
        """,
        (username, email, hash_password(password), int(role["id"])),
    )
    connection.commit()
    send_verification_email(connection, email)
    return {"status": "created", "message": "Hesabınız oluşturuldu. Giriş yapmadan önce e-posta adresinizi doğrulayın."}


def send_verification_email(connection: Any, email: str) -> dict[str, str]:
    ensure_account_security_schema(connection)
    user = _find_user_by_email(connection, email)
    if not user:
        raise ValueError("Bu e-posta adresi ile eşleşen kullanıcı bulunamadı.")
    if bool(user.get("email_verified")):
        return {"status": "already_verified", "message": "Bu kullanıcının e-postası zaten doğrulanmış."}
    consume_rate_limit(
        connection,
        "verification_send",
        str(user["email"]),
        VERIFICATION_SEND_RATE_LIMIT[0],
        VERIFICATION_SEND_RATE_LIMIT[1],
        "Çok fazla doğrulama kodu talebi alındı.",
    )
    code = _create_numeric_code()
    expires_at = datetime.now() + timedelta(hours=EMAIL_VERIFICATION_EXPIRY_HOURS)
    cursor = connection.cursor()
    cursor.execute("UPDATE email_verification_tokens SET used_at = NOW() WHERE user_id = %s AND used_at IS NULL", (user["id"],))
    cursor.execute(
        "INSERT INTO email_verification_tokens (user_id, token_hash, expires_at) VALUES (%s, %s, %s)",
        (user["id"], _token_hash(code), expires_at),
    )
    connection.commit()
    subject, body, html_body = _verification_email_content(str(user["kullanici_adi"]), code)
    return _send_email(str(user["email"]), subject, body, html_body)


def verify_email_code(connection: Any, email: str, code: str) -> dict[str, str]:
    ensure_account_security_schema(connection)
    email = validate_email(email)
    code = str(code or "").strip()
    if not code:
        raise ValueError("Doğrulama kodunu girin.")
    user = _find_user_by_email(connection, email)
    if not user:
        raise ValueError("Bu e-posta adresi ile eşleşen kullanıcı bulunamadı.")
    consume_rate_limit(
        connection,
        "verification_verify",
        email,
        VERIFICATION_VERIFY_RATE_LIMIT[0],
        VERIFICATION_VERIFY_RATE_LIMIT[1],
        "Çok fazla doğrulama denemesi yapıldı.",
    )
    cursor = connection.cursor(dictionary=True)
    cursor.execute(
        """
        SELECT id
        FROM email_verification_tokens
        WHERE user_id = %s AND token_hash = %s AND used_at IS NULL AND expires_at >= NOW()
        ORDER BY created_at DESC
        LIMIT 1
        """,
        (user["id"], _token_hash(code)),
    )
    row = cursor.fetchone()
    if not row:
        raise ValueError("Doğrulama kodu geçersiz veya süresi dolmuş.")
    cursor.execute(
        "UPDATE kullanicilar SET email_verified = TRUE, is_active = TRUE, email_verified_at = NOW() WHERE id = %s",
        (user["id"],),
    )
    cursor.execute("UPDATE email_verification_tokens SET used_at = NOW() WHERE id = %s", (row["id"],))
    connection.commit()
    return {"status": "verified", "message": "E-posta adresi doğrulandı. Hesap aktif hale getirildi."}


def send_password_reset_code(connection: Any, identifier: str) -> dict[str, str]:
    ensure_account_security_schema(connection)
    identifier = str(identifier or "").strip()
    if not identifier:
        raise ValueError("Kullanıcı adı veya e-posta girin.")
    user = _find_user_by_identifier(connection, identifier)
    if not user:
        raise ValueError("Bu bilgi ile eşleşen kullanıcı bulunamadı.")
    if not user.get("email"):
        raise ValueError("Bu kullanıcı için e-posta adresi tanımlı değil.")
    consume_rate_limit(
        connection,
        "password_reset_send",
        identifier,
        PASSWORD_RESET_SEND_RATE_LIMIT[0],
        PASSWORD_RESET_SEND_RATE_LIMIT[1],
        "Çok fazla şifre sıfırlama kodu talebi alındı.",
    )
    code = _create_numeric_code()
    expires_at = datetime.now() + timedelta(minutes=PASSWORD_RESET_EXPIRY_MINUTES)
    cursor = connection.cursor()
    cursor.execute("UPDATE password_reset_tokens SET used_at = NOW() WHERE user_id = %s AND used_at IS NULL", (user["id"],))
    cursor.execute(
        "INSERT INTO password_reset_tokens (user_id, reset_code_hash, expires_at) VALUES (%s, %s, %s)",
        (user["id"], _token_hash(code), expires_at),
    )
    connection.commit()
    subject, body, html_body = _password_reset_email_content(str(user["kullanici_adi"]), code)
    return _send_email(str(user["email"]), subject, body, html_body)


def reset_password_with_code(connection: Any, identifier: str, code: str, new_password: str) -> dict[str, str]:
    ensure_account_security_schema(connection)
    identifier = str(identifier or "").strip()
    code = str(code or "").strip()
    if not identifier:
        raise ValueError("Kullanıcı adı veya e-posta girin.")
    if not code:
        raise ValueError("Sıfırlama kodunu girin.")
    validate_password_policy(new_password)
    user = _find_user_by_identifier(connection, identifier)
    if not user:
        raise ValueError("Bu bilgi ile eşleşen kullanıcı bulunamadı.")
    consume_rate_limit(
        connection,
        "password_reset_verify",
        identifier,
        PASSWORD_RESET_VERIFY_RATE_LIMIT[0],
        PASSWORD_RESET_VERIFY_RATE_LIMIT[1],
        "Çok fazla şifre sıfırlama denemesi yapıldı.",
    )
    cursor = connection.cursor(dictionary=True)
    cursor.execute(
        """
        SELECT id
        FROM password_reset_tokens
        WHERE user_id = %s AND reset_code_hash = %s AND used_at IS NULL AND expires_at >= NOW()
        ORDER BY created_at DESC
        LIMIT 1
        """,
        (user["id"], _token_hash(code)),
    )
    row = cursor.fetchone()
    if not row:
        raise ValueError("Sıfırlama kodu geçersiz veya süresi dolmuş.")
    cursor.execute("UPDATE kullanicilar SET sifre_hash = %s WHERE id = %s", (hash_password(new_password), user["id"]))
    cursor.execute("UPDATE password_reset_tokens SET used_at = NOW() WHERE id = %s", (row["id"],))
    connection.commit()
    return {"status": "reset", "message": "Şifreniz başarıyla güncellendi."}
