ALTER TABLE kullanicilar ADD COLUMN IF NOT EXISTS mobile_module_permissions JSONB NULL;
ALTER TABLE kullanicilar ADD COLUMN IF NOT EXISTS manager_user_id BIGINT NULL REFERENCES kullanicilar(id) ON DELETE SET NULL;
ALTER TABLE kullanicilar ADD COLUMN IF NOT EXISTS leave_notification_email BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS image_url VARCHAR(500) NULL;
ALTER TABLE urunler ADD COLUMN IF NOT EXISTS basincli_hava_tuketimi NUMERIC(10, 2) NULL;

CREATE TABLE IF NOT EXISTS menu_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_key VARCHAR(100) NOT NULL UNIQUE,
    image_url VARCHAR(500) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NULL REFERENCES urunler(id) ON DELETE SET NULL,
    series_key VARCHAR(100) NULL,
    title VARCHAR(255) NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    language VARCHAR(5) NOT NULL DEFAULT 'tr',
    file_url VARCHAR(500) NOT NULL,
    description TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS urun_konfigurasyonlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teklif_no VARCHAR(40) UNIQUE,
    musteri_id BIGINT NOT NULL REFERENCES musteriler(id),
    created_by_user_id BIGINT NULL REFERENCES kullanicilar(id),
    urun_kategorisi VARCHAR(50) NOT NULL,
    base_product_id BIGINT NULL REFERENCES urunler(id),
    base_product_code VARCHAR(150),
    status VARCHAR(20) DEFAULT 'DRAFT',
    config_version INT,
    criteria_json JSONB,
    snapshot_json JSONB,
    subtotal_eur NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_eur NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax_eur NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_eur NUMERIC(12, 2) NOT NULL DEFAULT 0,
    client_total_eur NUMERIC(12, 2),
    para_birimi VARCHAR(3) NOT NULL DEFAULT 'EUR',
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    son_guncelleme_tarihi TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS urun_konfigurasyon_kalemleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    konfigurasyon_id BIGINT NOT NULL REFERENCES urun_konfigurasyonlari(id) ON DELETE CASCADE,
    display_order INT NOT NULL DEFAULT 0,
    item_tipi VARCHAR(100) NOT NULL,
    option_key VARCHAR(100),
    group_key VARCHAR(100),
    product_id BIGINT NULL REFERENCES urunler(id),
    product_code VARCHAR(150) NOT NULL,
    name VARCHAR(200),
    unit_price_eur NUMERIC(12, 2) NOT NULL DEFAULT 0,
    quantity INT NOT NULL DEFAULT 1,
    line_total_eur NUMERIC(12, 2) NOT NULL DEFAULT 0,
    metadata_json JSONB
);

CREATE TABLE IF NOT EXISTS servis_formlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_no VARCHAR(40) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES musteriler(id),
    product_serial_number VARCHAR(150) NOT NULL,
    product_model VARCHAR(255),
    service_personnel_name VARCHAR(150),
    status VARCHAR(20) NOT NULL DEFAULT 'FINAL',
    service_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    issue_description TEXT,
    service_actions TEXT,
    notes TEXT,
    signature_file_url VARCHAR(500),
    pdf_file_url VARCHAR(500),
    details_json JSONB,
    created_by_user_id BIGINT NULL REFERENCES kullanicilar(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
